# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

language: csharp
solution: ExifLibrary.sln

branches:
  only:
  - master

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
      os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      env: CONFIGURATION=Release
    - dotnet: 1.0.4
      mono: none
      os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Debug
    - dotnet: 1.0.4
      mono: none
      os: osx
      osx_image: xcode8.3
      env: CONFIGURATION=Release
    - dotnet: 1.0.4
      mono: none
      os: osx
      osx_image: xcode8.3
      env: CONFIGURATION=Debug

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "current ulimit is `ulimit -n`...";
      ulimit -n 1024;
      echo "new limit `ulimit -n`";
    fi
  - dotnet restore

script:
  - ls
  - dir
  - dotnet build -c $CONFIGURATION ExifLibrary\ExifLibrary.csproj

notifications:
  email: false